const images = {
    HOMEMENU: require('./home-menu.png'),
    CONNECTMENU: require('./bluetooth-menu.png'),
    CONTROLEMENU: require('./control-menu.png'),
    ROBOTMENU: require('./robot-menu.png'),
    id00b: require('./id-00-blue.png'),
    id01b: require('./id-01-blue.png'),
    id02b: require('./id-02-blue.png'),
    id03b: require('./id-03-blue.png'),
    id04b: require('./id-04-blue.png'),
    id05b: require('./id-05-blue.png'),
    id06b: require('./id-06-blue.png'),
    id07b: require('./id-07-blue.png'),
    id08b: require('./id-08-blue.png'),
    id09b: require('./id-09-blue.png'),
    id10b: require('./id-10-blue.png'),
    id11b: require('./id-11-blue.png'),
    id00y: require('./id-00-yellow.png'),
    id01y: require('./id-01-yellow.png'),
    id02y: require('./id-02-yellow.png'),
    id03y: require('./id-03-yellow.png'),
    id04y: require('./id-04-yellow.png'),
    id05y: require('./id-05-yellow.png'),
    id06y: require('./id-06-yellow.png'),
    id07y: require('./id-07-yellow.png'),
    id08y: require('./id-08-yellow.png'),
    id09y: require('./id-09-yellow.png'),
    id10y: require('./id-10-yellow.png'),
    id11y: require('./id-11-yellow.png')
};
export default images;